// SPDX-License-Identifier: AGPL-3.0-only
mod agency_controller;
mod auth;
mod error;
mod expression_review;
mod history_window;
mod llm_semantic_extractor;
mod memory_hygiene;
mod middleware;
mod openapi;
mod pipeline;
mod prompt;
mod prompt_log;
mod recall_controller;
mod repetition;
mod routes;
mod semantic_extractor;
mod semantic_review;
mod state;
mod window_exit;

use std::sync::Arc;

use anyhow::{Context, Result};
use axum::Router;
use utoipa::OpenApi;
use utoipa_axum::router::OpenApiRouter;
use utoipa_scalar::{Scalar, Servable};

use crate::auth::supabase::SupabaseJwtValidator;
use crate::auth::AuthValidator;
use crate::openapi::ApiDoc;
use crate::state::{AppState, ServerConfig};

#[tokio::main]
async fn main() -> Result<()> {
    // Pull `.env` into the process environment if present. Production
    // deployments (Fly.io secrets, Docker run --env, k8s secrets) won't
    // have a file here and dotenv() returns Err — we ignore it and fall
    // through to the real env. Local quickstart `cp .env.example .env`
    // now works without an explicit `set -a; source .env`.
    let _ = dotenvy::dotenv();

    // The workspace pins `tracing-subscriber` without the `env-filter` feature,
    // so we use the plain fmt initialiser. RUST_LOG is honoured via the
    // tracing-log bridge once the subscriber is installed.
    tracing_subscriber::fmt::init();

    // Subcommand dispatch.
    // Usage:
    //   eros-engine                       run the HTTP service (default)
    //   eros-engine serve                 same as above, explicit
    //   eros-engine migrate               apply sqlx migrations and exit
    //                                     (Fly.io release_command)
    //   eros-engine seed-personas <dir>   load every *.toml in <dir> as a
    //                                     persona genome (idempotent on name)
    //   eros-engine print-openapi         dump the OpenAPI spec to stdout and
    //                                     exit (no DB, no env). Used by the
    //                                     CI drift check.
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        Some("migrate") => run_migrations().await,
        Some("seed-personas") => {
            let dir = args
                .next()
                .unwrap_or_else(|| "/etc/eros-engine/personas".to_string());
            run_seed_personas(&dir).await
        }
        Some("print-openapi") => run_print_openapi(),
        Some("serve") | None => run_server().await,
        Some(other) => {
            eprintln!("unknown subcommand: {other}");
            eprintln!("usage: eros-engine [serve|migrate|seed-personas <dir>|print-openapi]");
            std::process::exit(2);
        }
    }
}

/// Dump the OpenAPI spec generated by utoipa to stdout. Pure compile-time
/// reflection — no DB pool, no env vars, no I/O beyond stdout. The CI
/// `openapi-snapshot` job diffs this against the committed snapshot to
/// catch handlers/types added without `#[utoipa::path]` / `ToSchema`.
fn run_print_openapi() -> Result<()> {
    let (_router, api) = OpenApiRouter::<crate::state::AppState>::with_openapi(ApiDoc::openapi())
        .merge(routes::router_for_openapi())
        .split_for_parts();
    let json = api
        .to_pretty_json()
        .context("serialize OpenAPI doc to JSON")?;
    println!("{json}");
    Ok(())
}

/// Read a directory of `*.toml` persona files and insert each into
/// `engine.persona_genomes`. Idempotent: rows are matched by `name`, so
/// re-running won't create duplicate rows — an existing row is updated in
/// place (id stable, content refreshed, FK references preserved).
async fn run_seed_personas(dir: &str) -> Result<()> {
    use serde::Deserialize;

    #[derive(Debug, Deserialize)]
    struct PersonaFile {
        name: String,
        tip_personality: Option<String>,
        system_prompt: String,
        #[serde(default)]
        art_metadata: serde_json::Value,
    }

    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL is required")?;
    let pool = eros_engine_store::pool::build(&database_url)
        .await
        .context("failed to connect to DATABASE_URL")?;
    let repo = eros_engine_store::persona::PersonaRepo { pool: &pool };

    let entries = std::fs::read_dir(dir).with_context(|| format!("read_dir({dir}) failed"))?;
    let mut inserted = 0u32;
    let mut skipped = 0u32;
    for entry in entries {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("toml") {
            continue;
        }
        let text = std::fs::read_to_string(&path).with_context(|| format!("read {path:?}"))?;
        let f: PersonaFile = toml::from_str(&text).with_context(|| format!("parse {path:?}"))?;

        let (id, created) = repo
            .upsert_genome(
                &f.name,
                &f.system_prompt,
                f.tip_personality.as_deref(),
                f.art_metadata,
            )
            .await
            .with_context(|| format!("upsert {}", f.name))?;
        if created {
            tracing::info!(name = %f.name, %id, "persona inserted");
            inserted += 1;
        } else {
            tracing::info!(name = %f.name, %id, "persona refreshed");
            skipped += 1;
        }
    }
    tracing::info!(inserted, skipped, "seed-personas complete");
    Ok(())
}

/// Apply all sqlx migrations and exit. Fly.io invokes this as the
/// release_command before swapping traffic to the new release.
async fn run_migrations() -> Result<()> {
    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL is required")?;
    let pool = eros_engine_store::pool::build(&database_url)
        .await
        .context("failed to connect to DATABASE_URL")?;
    tracing::info!("running migrations…");
    sqlx::migrate!("../eros-engine-store/migrations")
        .run(&pool)
        .await
        .context("sqlx migrate run failed")?;
    tracing::info!("migrations applied");
    Ok(())
}

async fn run_server() -> Result<()> {
    let cfg = ServerConfig::from_env();

    if let Some(dir) = cfg.prompt_log_dir.as_ref() {
        if let Err(e) = std::fs::create_dir_all(dir) {
            tracing::warn!(error = %e, dir = %dir.display(),
                "prompt logging: could not create PROMPT_LOG_DIR; writes may fail");
        }
        tracing::info!(dir = %dir.display(),
            "prompt logging ENABLED — writing raw assembled chat prompts to disk (operator-only)");
    }

    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL is required")?;
    let pool = eros_engine_store::pool::build(&database_url)
        .await
        .context("failed to connect to DATABASE_URL")?;

    // OpenRouter is optional.  The client is still constructed for backwards
    // compatibility, but an API key is only required when a configured task
    // actually routes a request through the built-in OpenRouter provider.
    // This lets deployments using a custom provider (for example DeepSeek,
    // Doubao, and a local embedding service) boot without an OpenRouter key.
    let openrouter_key = std::env::var("OPENROUTER_API_KEY").unwrap_or_default();

    // Auth: prefer JWKS (asymmetric, the post-2025 Supabase default) and
    // fall back to a legacy HS256 shared secret if one is configured. At
    // least one source must be wired or the server boots with a validator
    // that rejects every token (fail-closed).
    //
    // - SUPABASE_JWKS_URL: explicit override.
    // - SUPABASE_URL: derive `${SUPABASE_URL}/auth/v1/.well-known/jwks.json`.
    // - SUPABASE_JWT_SECRET: legacy HS256 shared secret (optional).
    let jwks_url = std::env::var("SUPABASE_JWKS_URL").ok().or_else(|| {
        std::env::var("SUPABASE_URL")
            .ok()
            .map(|u| format!("{}/auth/v1/.well-known/jwks.json", u.trim_end_matches('/')))
    });
    // Resolve+validate the sources before wiring anything: an empty
    // SUPABASE_JWT_SECRET counts as absent, so `SUPABASE_JWT_SECRET=""` with no
    // JWKS source fails fast here instead of booting a validator that silently
    // rejects every request.
    let legacy_secret = resolve_legacy_secret(
        jwks_url.is_some(),
        std::env::var("SUPABASE_JWT_SECRET").ok(),
    )?;

    let mut validator = SupabaseJwtValidator::new();
    if let Some(url) = jwks_url.as_deref() {
        validator = validator
            .with_jwks_url(url)
            .await
            .with_context(|| format!("failed to load Supabase JWKS from {url}"))?;
    }
    if let Some(secret) = legacy_secret {
        validator = validator.with_legacy_secret(secret);
    }
    let auth: Arc<dyn AuthValidator> = Arc::new(validator);

    // model_config: env override > examples/model_config.toml dev default.
    // The committed example is sanitized; the real config is opted into via
    // MODEL_CONFIG_PATH (single file — the docker/Dockerfile.fly image bakes
    // it in for prod) or MODEL_CONFIG_DIR (a directory of .toml fragments
    // merged at boot; duplicate sections are boot errors). Mutually exclusive.
    let source = eros_engine_llm::model_config::resolve_config_source(
        std::env::var("MODEL_CONFIG_PATH").ok(),
        std::env::var("MODEL_CONFIG_DIR").ok(),
    )
    .context("model_config source resolution failed")?;
    let model_config = Arc::new(match &source {
        eros_engine_llm::model_config::ConfigSource::File(p) => {
            eros_engine_llm::model_config::ModelConfig::from_toml_file(std::path::Path::new(p))
                .with_context(|| format!("model_config load failed: {p}"))?
        }
        eros_engine_llm::model_config::ConfigSource::Dir(d) => {
            eros_engine_llm::model_config::ModelConfig::from_toml_dir(std::path::Path::new(d))
                .with_context(|| format!("model_config load failed from dir: {d}"))?
        }
    });

    // Dead-config gate for the affinity evaluator (#210). Runs before the
    // variant-shape gate: this check is shape-independent (it only asks
    // whether the key exists), so a table-shaped filter_prompt under
    // [tasks.affinity_evaluation] gets the accurate "affinity's prompt is not
    // configurable" message instead of the generic "only the composer reads
    // variants" one.
    if let Err(msg) = model_config.validate_affinity_prompt_unset() {
        anyhow::bail!(msg);
    }

    // Same placement rationale as the affinity gate directly above: shape-
    // independent, so a variant-shaped filter_prompt under
    // [tasks.character_insight_structuring] gets the accurate "this prompt is
    // engine-owned" message rather than the generic variant one.
    if let Err(msg) = model_config.validate_structuring_prompt_unset() {
        anyhow::bail!(msg);
    }

    // Prompt-variant shape gate runs before the resolver-based checks below
    // (extraction / product_qa). Those detect "unset" via
    // `PromptSpec::as_plain()`, under which a variant shape (array/table)
    // reads as `None` — so a variant-shaped filter_prompt misplaced under, say,
    // [tasks.insight_extraction] would otherwise surface as "filter_prompt is
    // unset" (telling an operator who just set it to set it) instead of the
    // accurate "uses a variant shape, but only [tasks.chat_image_prompt_compose]
    // and [tasks.chat_image_edit_compose] read variants" from
    // `validate_prompt_variants`.
    if let Err(msg) = model_config.validate_prompt_variants() {
        anyhow::bail!(msg);
    }

    // Extraction prompts are required ONLY when the task section exists. A
    // missing [tasks.*_extraction] section means that extraction is off — the
    // engine boots and runs without it. A present section with a blank/absent
    // filter_prompt is a misconfiguration we refuse to boot on. Placed in the
    // serve path only (the print-openapi subcommand returns before reaching
    // here).
    if let Err(msg) = model_config.validate_extraction_prompts() {
        anyhow::bail!(msg);
    }

    if let Err(msg) = model_config.validate_voice_model() {
        anyhow::bail!(msg);
    }

    if let Err(msg) = model_config.validate_product_qa_prompt() {
        anyhow::bail!(msg);
    }

    // Multi-provider routing (spec 2026-07-31): [providers] table shape plus a
    // literal full scan of every candidate slug — grammar, declaredness, and
    // per-provider <NAME>_API_KEY presence. Refuses to boot on any miss.
    if let Err(msg) = model_config.validate_providers() {
        anyhow::bail!(msg);
    }

    // Dead-config gate for tier blocks under tasks that never resolve with a
    // tier (#215): only [tasks.chat_companion] and [tasks.chat_output_filter]
    // are ever resolved with one. Runs AFTER validate_providers on purpose —
    // that gate already refuses [tasks.embedding.tiers.*] with an
    // embedding-specific message, and the ordering rule is the same one that
    // puts validate_affinity_prompt_unset before validate_prompt_variants: the
    // more specific message is the one the operator gets to see.
    if let Err(msg) = model_config.validate_tier_blocks() {
        anyhow::bail!(msg);
    }

    // Sampling knobs (issue #246): an out-of-range value and any knob on
    // [tasks.embedding] are dead config the provider would clamp, ignore, or
    // 400 on inconsistently. Sits next to the tier gate because it refuses the
    // same class — config that parses, boots, and does nothing.
    if let Err(msg) = model_config.validate_sampling() {
        anyhow::bail!(msg);
    }

    // Embedding routing (spec 2026-08-01): read/write backends resolved from
    // [tasks.embedding] + [providers]. validate_providers has already gated
    // every failure mode; from_config re-checks keys defensively.
    let embed = Arc::new(
        eros_engine_llm::embedding::EmbeddingRouter::from_config(&model_config)
            .map_err(|e| anyhow::anyhow!("embedding router construction failed: {e}"))?,
    );

    if let Err(msg) = model_config.validate_removed_tasks() {
        anyhow::bail!(msg);
    }

    // Skip when the master switch is off — WORLD_DISABLED must be able to
    // isolate a staged/incomplete [tasks.world_director] section (the sweeper
    // won't spawn and injection is gated too, so a blank prompt is harmless).
    // WORLD_TOWN_DISABLED isolates the two town sections
    // ([tasks.world_comment] / [tasks.world_reply]) the same way: the town
    // sweeper won't spawn, so a staged/broken town config must not block boot.
    // WORLD_STORIES_DISABLED isolates the world_stories_director section the
    // same way: the story sweeper won't spawn and stories injection is gated
    // too, so a staged/broken stories config must not block boot.
    if !cfg.world.disabled {
        if let Err(msg) = model_config
            .validate_world_prompts(!cfg.world.town_disabled, !cfg.world.stories_disabled)
        {
            anyhow::bail!(msg);
        }
    }
    // Hard prerequisite (spec §1.1): product_qa is judge-routed only. With the
    // LLM PDE off the action is unreachable — warn once and stay inert rather
    // than refusing to boot ("此功能不启用").
    if model_config.product_qa_enabled() && !model_config.pde_enabled() {
        tracing::warn!(
            "model_config: [tasks.chat_product_qa] is configured but the LLM PDE \
             ([tasks.pde_decision].filter_prompt) is disabled — product_qa is inert"
        );
    }

    let output_regex = match model_config.compile_output_regex() {
        Ok(rules) => Arc::new(rules),
        Err(msg) => anyhow::bail!(msg),
    };

    // OpenRouter client is constructed after model_config so we can wire in the
    // [providers] endpoint map and the [providers].openrouter entry (chat URL
    // override + default headers, replacing the old OPENROUTER_BASE_URL /
    // OPENROUTER_APP_* env vars).
    let openrouter = Arc::new(
        eros_engine_llm::openrouter::OpenRouterClient::new(openrouter_key)
            .with_openrouter_chat_url(model_config.openrouter_chat_url())
            .with_openrouter_headers(model_config.openrouter_header_map())
            .with_providers(model_config.build_providers())
            .with_openrouter_body_rules(model_config.openrouter_body_rules()),
    );

    // Computed once at boot, before model_config is moved into the state
    // struct: gates fetch_world_context so an unconfigured deployment (no
    // [tasks.world_director] section) never runs the world JOIN per reply.
    let world_configured = model_config.resolve_world_director().is_some();
    let stories_configured = model_config.resolve_world_stories_director().is_some();

    let state = AppState {
        pool,
        auth,
        config: cfg.clone(),
        openrouter,
        embed,
        model_config,
        output_regex,
        stream_slots: Arc::new(crate::state::StreamSlots::default()),
        world_configured,
        stories_configured,
        chat_queue_notify: Arc::new(tokio::sync::Notify::new()),
    };

    // Compose the OpenAPI-aware router. routes::router applies the auth
    // middleware to /comp/* internally; healthz stays public. We seed
    // the spec with `ApiDoc::openapi()` so the title/servers/tags from
    // `openapi.rs` show up at /docs alongside the per-route paths.
    let (open_router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .merge(routes::router(state.clone()))
        .split_for_parts();

    // Spawn the dreaming-lite sweeper alongside the HTTP service. Returns
    // immediately when DREAMING_DISABLED=1 (or tick=0) is set, so unit
    // tests and self-hosters who want only synchronous behaviour can opt out.
    // Cloned because the next line moves `state` into the router.
    tokio::spawn(crate::pipeline::dreaming::sweeper(state.clone()));

    // human_insights_snapshot sweeper. Returns immediately when
    // SNAPSHOT_DISABLED=1 or the cron expression fails to parse, so the
    // chat path is unaffected by snapshot misconfig.
    tokio::spawn(crate::pipeline::snapshot::sweeper(state.clone()));

    // World Memories director sweeper. Inert when WORLD_DISABLED=1/true or
    // [tasks.world_director] is absent/blank (spec §2.1).
    tokio::spawn(crate::pipeline::world::sweeper(state.clone()));

    // World Town sweeper (posts feed). Inert when the world subsystem is off,
    // WORLD_TOWN_DISABLED is set, or [tasks.world_director] is absent — no
    // posts can exist without the director (town spec §3).
    tokio::spawn(crate::pipeline::world_town::sweeper(state.clone()));

    // Chat-queue worker: drives async-endpoint turns (spec
    // 2026-08-20-async-chat-endpoint-design). Inert when CHAT_QUEUE_DISABLED.
    tokio::spawn(crate::pipeline::chat_queue::worker(state.clone()));

    let app: Router = open_router
        .with_state(state)
        .merge(Scalar::with_url("/docs", api))
        .layer(crate::middleware::SseHeadersLayer)
        .layer(tower_http::trace::TraceLayer::new_for_http());

    let listener = tokio::net::TcpListener::bind(&cfg.bind_addr).await?;
    tracing::info!(
        addr = %cfg.bind_addr,
        "eros-engine starting"
    );
    axum::serve(listener, app).await?;
    Ok(())
}

/// Validates the configured JWT sources and returns the legacy HS256 secret to
/// wire, if any. A *non-empty* `SUPABASE_JWT_SECRET` is the only thing that
/// counts as the legacy source — an empty one is treated as absent, so the boot
/// guard agrees with what actually gets wired. Returns an error (fail-fast at
/// boot) when neither a JWKS source nor a non-empty legacy secret is present;
/// otherwise the server would boot a validator that rejects every token.
fn resolve_legacy_secret(has_jwks: bool, jwt_secret: Option<String>) -> Result<Option<String>> {
    let legacy_secret = jwt_secret.filter(|s| !s.is_empty());
    if !has_jwks && legacy_secret.is_none() {
        anyhow::bail!(
            "no JWT validation source configured: set SUPABASE_URL (preferred) \
             or SUPABASE_JWKS_URL for asymmetric JWT validation, and/or \
             SUPABASE_JWT_SECRET for the legacy HS256 path"
        );
    }
    Ok(legacy_secret)
}

#[cfg(test)]
mod tests {
    use super::resolve_legacy_secret;
    use eros_engine_llm::model_config::ModelConfig;

    /// The committed example config is the dev/prod boot default; it MUST pass the
    /// extraction boot gate (both sections present with non-blank filter_prompts),
    /// or `main` bails.
    #[test]
    fn shipped_model_config_satisfies_extraction_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        assert!(
            cfg.validate_extraction_prompts().is_ok(),
            "shipped config must pass the extraction boot gate: {:?}",
            cfg.validate_extraction_prompts()
        );
    }

    #[test]
    fn shipped_model_config_satisfies_product_qa_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = eros_engine_llm::model_config::ModelConfig::from_toml_str(text)
            .expect("shipped example parses");
        cfg.validate_product_qa_prompt()
            .expect("shipped example must pass the product_qa boot gate");
    }

    /// The shipped example's [tasks.chat_image_prompt_compose] override is
    /// commented out, and every other task in it uses a plain filter_prompt —
    /// it MUST pass the variant-shape boot gate, or `main` bails.
    #[test]
    fn shipped_model_config_satisfies_prompt_variant_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        assert!(
            cfg.validate_prompt_variants().is_ok(),
            "shipped config must pass the prompt-variant boot gate: {:?}",
            cfg.validate_prompt_variants()
        );
    }

    /// The shipped example's [tasks.affinity_evaluation] block carries model /
    /// fallback / temperature / max_tokens and deliberately NO filter_prompt —
    /// it MUST pass the affinity dead-config gate, or `main` bails (#210).
    #[test]
    fn shipped_model_config_satisfies_affinity_prompt_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        cfg.validate_affinity_prompt_unset()
            .expect("shipped example must not set an affinity filter_prompt");
    }

    /// The shipped example's [tasks.character_insight_structuring] block is
    /// parameters-only by design — it MUST pass the structuring dead-config
    /// gate, or `main` bails on the config we tell people to copy.
    #[test]
    fn shipped_model_config_satisfies_structuring_prompt_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        cfg.validate_structuring_prompt_unset()
            .expect("shipped example must not set a structuring filter_prompt");
    }

    /// Every `[tasks.*.tiers.*]` block in the shipped example is commented out
    /// (both `chat_companion`'s and `chat_output_filter`'s), so it MUST pass
    /// the tier dead-config gate, or `main` bails (#215).
    #[test]
    fn shipped_model_config_satisfies_tier_block_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        cfg.validate_tier_blocks()
            .expect("shipped example must not carry a tier block on a non-tiering task");
    }

    /// The shipped example sets sampling knobs on [tasks.chat_companion] only,
    /// all in range, and none on [tasks.embedding] — it MUST pass the sampling
    /// boot gate, or `main` bails (#246).
    #[test]
    fn shipped_model_config_satisfies_sampling_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        cfg.validate_sampling()
            .expect("shipped example must pass the sampling boot gate");
    }

    #[test]
    fn shipped_model_config_passes_removed_task_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        cfg.validate_removed_tasks()
            .expect("shipped example must not carry removed task blocks");
    }

    /// Regression for the boot-check ordering bug: `validate_extraction_prompts`
    /// detects "unset" via `PromptSpec::as_plain()`, under which a variant shape
    /// reads as `None` — so, checked in isolation, it produces a misleading
    /// "filter_prompt is unset" message for a variant-shaped
    /// [tasks.insight_extraction], instead of the accurate "uses a variant
    /// shape" one from `validate_prompt_variants`. `main` must run
    /// `validate_prompt_variants()` BEFORE `validate_extraction_prompts()` so
    /// the accurate message is the one an operator actually sees.
    #[test]
    fn variant_shaped_extraction_prompt_reports_the_accurate_error() {
        let cfg = ModelConfig::from_toml_str(
            "[tasks.insight_extraction]\nmodel = \"m\"\nfilter_prompt = [\"a\", \"b\"]\n",
        )
        .expect("parses");

        let variant_err = cfg
            .validate_prompt_variants()
            .expect_err("variant shape under insight_extraction must refuse to boot");
        assert!(variant_err.contains("variant shape"), "{variant_err}");
        assert!(variant_err.contains("insight_extraction"), "{variant_err}");
        assert!(
            !variant_err.contains("unset"),
            "the accurate message must not also claim the prompt is unset: {variant_err}"
        );

        // Sanity: pins the exact masking bug this ordering fix prevents —
        // checked on its own (the pre-fix order), the extraction gate sees the
        // variant shape as "unset" and reports the wrong, misleading reason.
        let unset_err = cfg
            .validate_extraction_prompts()
            .expect_err("extraction gate also errors on this config, but for the wrong reason");
        assert!(unset_err.contains("unset"), "{unset_err}");
    }

    /// Ordering regression, sibling of the one above and the reason
    /// `validate_structuring_prompt_unset` sits BEFORE `validate_prompt_variants`
    /// in `main`. A variant-shaped `[tasks.character_insight_structuring]
    /// .filter_prompt` trips both gates, so whichever runs first is the message
    /// the operator actually sees. The structuring gate's is the actionable one:
    /// it says the prompt is engine-owned and names the stage-1 key to edit
    /// instead. The variant gate only reports that variants are unreadable here,
    /// which would send an operator off to fix the shape of a key that must not
    /// exist at all.
    #[test]
    fn variant_shaped_structuring_prompt_reports_the_actionable_error() {
        let cfg = ModelConfig::from_toml_str(
            "[tasks.character_insight_structuring]\nmodel = \"m\"\n\
             filter_prompt = { a = \"x\", b = \"y\" }\n",
        )
        .expect("parses");

        let gate_err = cfg
            .validate_structuring_prompt_unset()
            .expect_err("a variant-shaped structuring prompt must refuse to boot");
        assert!(gate_err.contains("engine-owned"), "{gate_err}");
        assert!(
            gate_err.contains("[tasks.character_insight_extraction].filter_prompt"),
            "the message an operator sees must name the key that IS configurable: {gate_err}"
        );

        // Pins the masking this ordering prevents: the variant gate also errors
        // on this config, but its message is about prompt SHAPE — advice for a
        // key that should simply be deleted.
        let variant_err = cfg
            .validate_prompt_variants()
            .expect_err("the variant gate also rejects this config, for a shallower reason");
        assert!(
            !variant_err.contains("engine-owned"),
            "if the variant gate ever gained the actionable wording, this ordering \
             test stops meaning anything: {variant_err}"
        );
    }

    #[test]
    fn example_config_output_regex_compiles() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        assert!(
            cfg.compile_output_regex().is_ok(),
            "shipped example output_regex must compile: {:?}",
            cfg.compile_output_regex().err()
        );
    }

    #[test]
    fn no_source_bails() {
        assert!(resolve_legacy_secret(false, None).is_err());
    }

    #[test]
    fn empty_secret_without_jwks_bails() {
        // The regression: a present-but-empty SUPABASE_JWT_SECRET with no JWKS
        // source must fail fast, not boot an all-reject validator.
        assert!(resolve_legacy_secret(false, Some(String::new())).is_err());
    }

    #[test]
    fn jwks_alone_is_enough_and_wires_no_legacy_secret() {
        let secret = resolve_legacy_secret(true, None).expect("jwks source is sufficient");
        assert_eq!(secret, None);
    }

    #[test]
    fn empty_secret_with_jwks_is_ok_but_not_wired() {
        let secret =
            resolve_legacy_secret(true, Some(String::new())).expect("jwks source is sufficient");
        assert_eq!(
            secret, None,
            "empty secret must not be wired as legacy source"
        );
    }

    #[test]
    fn nonempty_secret_alone_is_enough_and_is_returned() {
        let secret = resolve_legacy_secret(false, Some("shh".to_string()))
            .expect("a non-empty legacy secret is a valid source");
        assert_eq!(secret.as_deref(), Some("shh"));
    }
}
