// SPDX-License-Identifier: AGPL-3.0-only
//! POST /v2/comp/session/{session_id}/message/async — enqueue-only chat turn.
//!
//! Spec: docs/superpowers/specs/2026-08-20-async-chat-endpoint-design.md
//! Renamed from /v2/comp/chat/{session_id}/message/async by the v2 convention
//! (docs/superpowers/specs/2026-08-22-user-insights-and-api-v2-design.md §4.6);
//! the old path was removed in 1.6.0 (see docs/migrating/v1-6-0-async-chat.md).
//! The /v2 prefix exists to avoid any confusion with the long-removed
//! /comp/chat/{id}/message_async endpoint (deleted in v0.2.0, a3f86ea).

use axum::extract::{Extension, Path, State};
use axum::http::StatusCode;
use axum::Json;
use serde::{Deserialize, Serialize};
use utoipa_axum::{router::OpenApiRouter, routes};
use uuid::Uuid;

use eros_engine_core::scope::MemoryScope;
use eros_engine_store::chat::ChatRepo;
use eros_engine_store::chat_queue::{ChatQueueRepo, EnqueueOutcome};

use crate::auth::middleware::AuthUser;
use crate::error::{AppError, StreamPreError};
use crate::routes::companion::{
    validate_llm_audit, validate_prompt_traits, LlmAuditDto, PromptTraitDto,
};
use crate::routes::companion_stream::{
    build_user_row_metadata, persisted_content_role, resolve_quote, resolve_text_turn,
    validate_image_capability, validate_payload, AffinityScopeDto, ImageReplyParams,
    StreamPreErrorBody, StreamSendRequest,
};
use crate::state::AppState;

/// Per-turn request knobs snapshotted into `chat_turn_queue.params` at
/// enqueue time and replayed by the worker at generation time. Field-for-field
/// the optional tail of `StreamSendRequest`.
#[derive(Debug, Default, Serialize, Deserialize)]
pub(crate) struct QueuedTurnParams {
    #[serde(default)]
    pub tier: Option<String>,
    #[serde(default)]
    pub memory_scope: Option<MemoryScope>,
    #[serde(default)]
    pub affinity_scope: Option<AffinityScopeDto>,
    #[serde(default)]
    pub prompt_traits: Option<Vec<PromptTraitDto>>,
    #[serde(default)]
    pub audit: Option<LlmAuditDto>,
    #[serde(default)]
    pub tips_amount_usd: Option<f64>,
    #[serde(default)]
    pub image_url: Option<String>,
    #[serde(default)]
    pub image: Option<ImageReplyParams>,
    #[serde(default)]
    pub reply_to_message_id: Option<Uuid>,
    /// The caller's optional `manual_memory` block, snapshotted with the turn
    /// so a worker re-drive writes exactly the memory the request asked for.
    #[serde(default)]
    pub manual_memory: Option<eros_engine_core::event_memory::ManualMemoryRequest>,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct AsyncSendResponse {
    /// `queued` | `already_queued` | `already_completed` | `failed`
    pub status: String,
    #[schema(value_type = String)]
    pub user_message_id: Uuid,
}

/// Enqueue a chat turn for asynchronous delivery.
///
/// Validates and persists the user message, then hands the turn to a
/// background worker; the assistant reply is generated out-of-band and lands
/// in this session's history over whatever channel the client already polls
/// or subscribes to (SSE / GET history) — this endpoint itself never returns
/// reply content. Idempotent on `client_msg_id`: redelivering a turn that is
/// already queued, completed, or terminally failed returns that outcome
/// instead of enqueueing a duplicate.
#[utoipa::path(
    post,
    path = "/v2/comp/session/{session_id}/message/async",
    tag = "companion",
    params(("session_id" = Uuid, Path, description = "Chat session id")),
    request_body = StreamSendRequest,
    responses(
        (status = 202, description = "Turn enqueued (`queued`) or an idempotent \
            redelivery of a turn still being handled (`already_queued`). The reply \
            is generated by a background worker and lands in this session's \
            history; no reply content is ever returned here.", body = AsyncSendResponse),
        (status = 200, description = "Idempotent replay: this client_msg_id was \
            already processed (`already_completed`) or terminally failed \
            (`failed`).", body = AsyncSendResponse),
        (status = 400, body = StreamPreErrorBody),
        (status = 401, description = "missing or invalid bearer"),
        (status = 403, body = StreamPreErrorBody),
        (status = 404, body = StreamPreErrorBody),
        (status = 409, body = StreamPreErrorBody),
        (status = 422, body = StreamPreErrorBody),
        (status = 429, body = StreamPreErrorBody),
    ),
    security(("bearer" = []))
)]
pub async fn send_message_async(
    State(state): State<AppState>,
    Path(session_id): Path<Uuid>,
    Extension(AuthUser(user_id)): Extension<AuthUser>,
    Json(req): Json<StreamSendRequest>,
) -> Result<(StatusCode, Json<AsyncSendResponse>), AppError> {
    validate_payload(&req)?;
    validate_image_capability(&req, &state.model_config)?;
    // Validate now so a bad request 400s at enqueue, not silently in the
    // worker; the raw DTOs (not the validated outputs) go into params and the
    // worker re-runs these same pure fns.
    validate_prompt_traits(req.prompt_traits.as_deref().unwrap_or(&[])).map_err(|e| {
        AppError::StreamPre(StreamPreError {
            status: StatusCode::BAD_REQUEST,
            code: "invalid_payload",
            message: e.to_string(),
            user_message: "请求无效".into(),
            original_user_message_id: None,
        })
    })?;
    validate_llm_audit(req.audit.clone()).map_err(|e| {
        AppError::StreamPre(StreamPreError {
            status: StatusCode::BAD_REQUEST,
            code: "invalid_payload",
            message: e.to_string(),
            user_message: "请求无效".into(),
            original_user_message_id: None,
        })
    })?;

    let (_session, _persona, _instance_id) = resolve_text_turn(&state, session_id, user_id).await?;

    let chat_repo = ChatRepo { pool: &state.pool };
    let quote = resolve_quote(&chat_repo, session_id, req.reply_to_message_id).await?;
    let persisted_metadata = build_user_row_metadata(&req, quote.as_ref());
    let (persisted_content, persisted_role) = persisted_content_role(&req);

    let params = serde_json::to_value(QueuedTurnParams {
        tier: req.tier.clone(),
        memory_scope: req.memory_scope,
        affinity_scope: req.affinity_scope,
        prompt_traits: req.prompt_traits,
        audit: req.audit,
        tips_amount_usd: req.tips_amount_usd,
        image_url: req.image_url,
        image: req.image,
        reply_to_message_id: req.reply_to_message_id,
        manual_memory: req.manual_memory,
    })
    .expect("QueuedTurnParams serializes");

    let queue_repo = ChatQueueRepo { pool: &state.pool };
    let outcome = queue_repo
        .enqueue_user_message(
            session_id,
            &persisted_content,
            &req.client_msg_id,
            persisted_role,
            persisted_metadata.as_ref(),
            user_id,
            &params,
            state.config.chat_queue.pending_cap,
        )
        .await?;

    let (status, body) = match outcome {
        EnqueueOutcome::Queued {
            user_message_id, ..
        } => {
            state.chat_queue_notify.notify_one();
            (
                StatusCode::ACCEPTED,
                AsyncSendResponse {
                    status: "queued".into(),
                    user_message_id,
                },
            )
        }
        EnqueueOutcome::AlreadyQueued { user_message_id } => (
            StatusCode::ACCEPTED,
            AsyncSendResponse {
                status: "already_queued".into(),
                user_message_id,
            },
        ),
        EnqueueOutcome::AlreadyCompleted { user_message_id } => (
            StatusCode::OK,
            AsyncSendResponse {
                status: "already_completed".into(),
                user_message_id,
            },
        ),
        EnqueueOutcome::Failed { user_message_id } => (
            StatusCode::OK,
            AsyncSendResponse {
                status: "failed".into(),
                user_message_id,
            },
        ),
        EnqueueOutcome::DepthExceeded => {
            return Err(AppError::StreamPre(StreamPreError {
                status: StatusCode::TOO_MANY_REQUESTS,
                code: "rate_limited",
                message: format!(
                    "per-session pending cap reached ({})",
                    state.config.chat_queue.pending_cap
                ),
                user_message: "请求过多，请稍后再试".into(),
                original_user_message_id: None,
            }));
        }
    };
    Ok((status, Json(body)))
}

pub fn router() -> OpenApiRouter<AppState> {
    OpenApiRouter::new().routes(routes!(send_message_async))
}

#[cfg(test)]
mod tests {
    use axum::body::{to_bytes, Body};
    use axum::http::{header, Request, StatusCode};
    use axum::Router;
    use serde_json::{json, Value};
    use sqlx::PgPool;
    use tower::Service;
    use uuid::Uuid;

    use crate::routes::companion::test_state;
    use crate::routes::companion::testutil::{
        build_router, mint_test_jwt, seed_genome, seed_instance, seed_session,
    };

    fn async_uri(session_id: Uuid) -> String {
        format!("/v2/comp/session/{session_id}/message/async")
    }

    async fn post_json(
        app: &mut Router,
        uri: &str,
        token: &str,
        body: Value,
    ) -> (StatusCode, Value) {
        let req = Request::builder()
            .method("POST")
            .uri(uri)
            .header(header::AUTHORIZATION, format!("Bearer {token}"))
            .header(header::CONTENT_TYPE, "application/json")
            .body(Body::from(serde_json::to_vec(&body).unwrap()))
            .unwrap();
        let resp = app.call(req).await.unwrap();
        let status = resp.status();
        let bytes = to_bytes(resp.into_body(), 1024 * 1024).await.unwrap();
        let v: Value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap()
        };
        (status, v)
    }

    // Test 1: fresh enqueue → 202 {"status":"queued"}, user row + pending
    // queue row exist.
    #[sqlx::test(migrations = "../eros-engine-store/migrations")]
    async fn async_202_queued_on_fresh_enqueue(pool: PgPool) {
        let user_id = Uuid::new_v4();
        let genome_id = seed_genome(&pool, "Aria").await;
        let instance_id = seed_instance(&pool, genome_id, user_id).await;
        let session_id = seed_session(&pool, user_id, instance_id).await;

        let mut app = build_router(test_state(pool.clone()));
        let token = mint_test_jwt(user_id);

        let (status, body) = post_json(
            &mut app,
            &async_uri(session_id),
            &token,
            json!({"content":"hi","client_msg_id":"01JV000000000000000000001A"}),
        )
        .await;
        assert_eq!(status, StatusCode::ACCEPTED, "body: {body}");
        assert_eq!(body["status"], "queued");
        let user_message_id =
            Uuid::parse_str(body["user_message_id"].as_str().expect("uuid string"))
                .expect("user_message_id is a valid uuid");

        let pending: i64 = sqlx::query_scalar(
            "SELECT count(*) FROM engine.chat_turn_queue WHERE session_id = $1 AND status = 'pending'",
        )
        .bind(session_id)
        .fetch_one(&pool)
        .await
        .unwrap();
        assert_eq!(pending, 1);

        let content: String =
            sqlx::query_scalar("SELECT content FROM engine.chat_messages WHERE id = $1")
                .bind(user_message_id)
                .fetch_one(&pool)
                .await
                .unwrap();
        assert_eq!(content, "hi");
    }

    // Test 2: redelivery of the same client_msg_id → 202
    // {"status":"already_queued"}, still one queue row.
    #[sqlx::test(migrations = "../eros-engine-store/migrations")]
    async fn async_202_already_queued_on_redelivery(pool: PgPool) {
        let user_id = Uuid::new_v4();
        let genome_id = seed_genome(&pool, "Aria").await;
        let instance_id = seed_instance(&pool, genome_id, user_id).await;
        let session_id = seed_session(&pool, user_id, instance_id).await;

        let mut app = build_router(test_state(pool.clone()));
        let token = mint_test_jwt(user_id);
        let payload = json!({"content":"hi","client_msg_id":"01JV000000000000000000002A"});

        let (first_status, first_body) =
            post_json(&mut app, &async_uri(session_id), &token, payload.clone()).await;
        assert_eq!(first_status, StatusCode::ACCEPTED, "body: {first_body}");
        assert_eq!(first_body["status"], "queued");

        let (second_status, second_body) =
            post_json(&mut app, &async_uri(session_id), &token, payload).await;
        assert_eq!(second_status, StatusCode::ACCEPTED, "body: {second_body}");
        assert_eq!(second_body["status"], "already_queued");
        assert_eq!(
            second_body["user_message_id"], first_body["user_message_id"],
            "redelivery must resolve to the same persisted user row"
        );

        let pending: i64 = sqlx::query_scalar(
            "SELECT count(*) FROM engine.chat_turn_queue WHERE session_id = $1 AND status = 'pending'",
        )
        .bind(session_id)
        .fetch_one(&pool)
        .await
        .unwrap();
        assert_eq!(pending, 1, "redelivery must not create a second queue row");
    }

    // Test 3: completed replay → 200 {"status":"already_completed"}.
    #[sqlx::test(migrations = "../eros-engine-store/migrations")]
    async fn async_200_already_completed_on_replay(pool: PgPool) {
        use eros_engine_store::chat::{AssistantInsert, ChatRepo, UpsertUserOutcome};

        let user_id = Uuid::new_v4();
        let genome_id = seed_genome(&pool, "Aria").await;
        let instance_id = seed_instance(&pool, genome_id, user_id).await;
        let session_id = seed_session(&pool, user_id, instance_id).await;

        // Pre-seed an already-completed turn: a user row plus an assistant
        // reply chained off it, exactly as the sync stream path would leave
        // behind — the async endpoint must recognise this client_msg_id as
        // already handled rather than re-enqueueing it.
        let chat_repo = ChatRepo { pool: &pool };
        let user_msg_id = match chat_repo
            .upsert_user_message_idempotent(
                session_id,
                "hi",
                "01JV000000000000000000003A",
                "user",
                None,
            )
            .await
            .unwrap()
        {
            UpsertUserOutcome::Inserted { message_id } => message_id,
            _ => unreachable!(),
        };
        // Since 0060 chat_messages.generation_id FK-references
        // engine.llm_generations. Release A's write path creates the parent;
        // this test writes the child row directly, so it seeds one itself.
        sqlx::query(
            "INSERT INTO engine.llm_generations (generation_id, task) \
             VALUES ('gen-1', 'chat_companion')",
        )
        .execute(&pool)
        .await
        .unwrap();
        let assistant_uuid: Uuid = ulid::Ulid::new().into();
        chat_repo
            .insert_assistant_batch(
                session_id,
                user_msg_id,
                &[AssistantInsert {
                    llm_attempts: None,
                    gateway_errors: None,
                    id: assistant_uuid,
                    content: "already replied".into(),
                    assistant_action_type: "reply".into(),
                    continues_from_message_id: None,
                    truncated: false,
                    generation_id: Some("gen-1".into()),
                    filter_audit: None,
                    metadata: None,
                }],
            )
            .await
            .unwrap();

        let mut app = build_router(test_state(pool.clone()));
        let token = mint_test_jwt(user_id);
        let (status, body) = post_json(
            &mut app,
            &async_uri(session_id),
            &token,
            json!({"content":"hi","client_msg_id":"01JV000000000000000000003A"}),
        )
        .await;
        assert_eq!(status, StatusCode::OK, "body: {body}");
        assert_eq!(body["status"], "already_completed");
        assert_eq!(body["user_message_id"], json!(user_msg_id.to_string()));
    }

    // Test 4: per-session pending cap → the first `pending_cap` distinct
    // turns enqueue (202), the next one 429s {"code":"rate_limited"} and
    // persists no chat_messages row for the rejected client_msg_id.
    #[sqlx::test(migrations = "../eros-engine-store/migrations")]
    async fn async_429_when_pending_cap_reached(pool: PgPool) {
        let user_id = Uuid::new_v4();
        let genome_id = seed_genome(&pool, "Aria").await;
        let instance_id = seed_instance(&pool, genome_id, user_id).await;
        let session_id = seed_session(&pool, user_id, instance_id).await;

        let mut state = test_state(pool.clone());
        state.config.chat_queue.pending_cap = 2;
        let mut app = build_router(state);
        let token = mint_test_jwt(user_id);

        for n in 1..=2 {
            let client_msg_id = format!("01JV00000000000000000001{n}A");
            let (status, body) = post_json(
                &mut app,
                &async_uri(session_id),
                &token,
                json!({"content": format!("turn {n}"), "client_msg_id": client_msg_id}),
            )
            .await;
            assert_eq!(status, StatusCode::ACCEPTED, "turn {n} body: {body}");
            assert_eq!(body["status"], "queued");
        }

        let rejected_client_msg_id = "01JV000000000000000000013A";
        let (status, body) = post_json(
            &mut app,
            &async_uri(session_id),
            &token,
            json!({"content":"one too many","client_msg_id": rejected_client_msg_id}),
        )
        .await;
        assert_eq!(status, StatusCode::TOO_MANY_REQUESTS, "body: {body}");
        assert_eq!(body["code"], "rate_limited");

        let rows: i64 = sqlx::query_scalar(
            "SELECT count(*) FROM engine.chat_messages WHERE session_id = $1 AND client_msg_id = $2",
        )
        .bind(session_id)
        .bind(rejected_client_msg_id)
        .fetch_one(&pool)
        .await
        .unwrap();
        assert_eq!(rows, 0, "depth-capped turn must not persist a message row");
    }

    // Test 5: voice-channel session → 409 {"code":"wrong_channel"}, nothing
    // persisted.
    #[sqlx::test(migrations = "../eros-engine-store/migrations")]
    async fn async_409_when_session_is_voice_channel(pool: PgPool) {
        let user_id = Uuid::new_v4();
        let genome_id = seed_genome(&pool, "Aria").await;
        let instance_id = seed_instance(&pool, genome_id, user_id).await;
        let session_id: Uuid = sqlx::query_scalar(
            "INSERT INTO engine.chat_sessions (user_id, instance_id, channel) \
             VALUES ($1, $2, 'voice') RETURNING id",
        )
        .bind(user_id)
        .bind(instance_id)
        .fetch_one(&pool)
        .await
        .unwrap();

        let mut app = build_router(test_state(pool.clone()));
        let token = mint_test_jwt(user_id);
        let (status, body) = post_json(
            &mut app,
            &async_uri(session_id),
            &token,
            json!({"content":"typed","client_msg_id":"01JV000000000000000000004A"}),
        )
        .await;
        assert_eq!(status, StatusCode::CONFLICT, "body: {body}");
        assert_eq!(body["code"], "wrong_channel");

        let rows: i64 =
            sqlx::query_scalar("SELECT count(*) FROM engine.chat_messages WHERE session_id = $1")
                .bind(session_id)
                .fetch_one(&pool)
                .await
                .unwrap();
        assert_eq!(rows, 0, "a rejected async turn must not persist any row");
    }

    // The pre-rename path is gone from the spec, not merely unrouted: a
    // consumer reading openapi.json must see exactly one async path.
    #[test]
    fn openapi_has_no_legacy_async_path() {
        let spec = crate::routes::openapi_for_tests();
        let paths = spec["paths"].as_object().expect("paths object");

        assert!(
            paths.contains_key("/v2/comp/session/{session_id}/message/async"),
            "canonical async path must be in the spec"
        );
        assert!(
            !paths.contains_key("/v2/comp/chat/{session_id}/message/async"),
            "the removed /v2/comp/chat alias must not be in the spec"
        );
    }
}
